#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = smtp.gmail.com:587
user = anishkarki989@gmail.com
password = eMiLio#352
; If using Gmail, you need an "App Password" from your Google account
from_address = anishkarki989@gmail.com
from_name = Grafana Alerts
skip_verify = false
